owner: wakatime
repo: statuspage
user-agent: alanhamlett
sites:
  - name: Website
    url: https://wakatime.com
  - name: API
    url: https://api.wakatime.com/api/v1/meta
notifications:
  - type: slack
    channel: C01CHHXFQ3E
assignees:
  - alanhamlett
status-website:
  cname: status.wakatime.com
  logoUrl: https://avatars0.githubusercontent.com/u/4814844?s=200&v=4
  name: WakaTime
  introTitle: "WakaTime Status"
  introMessage: This page shows **real-time** status of the WakaTime website and api.
